export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      products_catalog: {
        Row: {
          id: string;
          sku: string;
          description: string;
          box_sf: number;
          box_edgeband: number | null;
          box_edgeband_color: number | null;
          doors_fronts_sf: number;
          doors_fronts_edgeband: number | null;
          total_edgeband: number;
          has_drawers: boolean;
          is_active: boolean;
          original_box_sf: number | null;
          original_doors_fronts_sf: number | null;
          waste_applied: boolean | null;
          custom_labor_cost: number | null;
          boxes_per_unit: number;
          default_is_rta: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sku: string;
          description: string;
          box_sf: number;
          box_edgeband?: number | null;
          box_edgeband_color?: number | null;
          doors_fronts_sf: number;
          doors_fronts_edgeband?: number | null;
          total_edgeband: number;
          has_drawers?: boolean;
          is_active?: boolean;
          original_box_sf?: number | null;
          original_doors_fronts_sf?: number | null;
          waste_applied?: boolean | null;
          custom_labor_cost?: number | null;
          boxes_per_unit?: number;
          default_is_rta?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          sku?: string;
          description?: string;
          box_sf?: number;
          box_edgeband?: number | null;
          box_edgeband_color?: number | null;
          doors_fronts_sf?: number;
          doors_fronts_edgeband?: number | null;
          total_edgeband?: number;
          has_drawers?: boolean;
          is_active?: boolean;
          original_box_sf?: number | null;
          original_doors_fronts_sf?: number | null;
          waste_applied?: boolean | null;
          custom_labor_cost?: number | null;
          boxes_per_unit?: number;
          default_is_rta?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      price_list: {
        Row: {
          id: string;
          sku_code: string | null;
          concept_description: string;
          type: string;
          material: string | null;
          dimensions: string | null;
          unit: string;
          price: number;
          sf_per_sheet: number | null;
          tax_rate: number | null;
          base_price: number | null;
          price_with_tax: number | null;
          product_url: string | null;
          image_url: string | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          price_last_updated_at: string;
        };
        Insert: {
          id?: string;
          sku_code?: string | null;
          concept_description: string;
          type: string;
          material?: string | null;
          dimensions?: string | null;
          unit: string;
          price: number;
          sf_per_sheet?: number | null;
          tax_rate?: number | null;
          base_price?: number | null;
          price_with_tax?: number | null;
          product_url?: string | null;
          image_url?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          price_last_updated_at?: string;
        };
        Update: {
          id?: string;
          sku_code?: string | null;
          concept_description?: string;
          type?: string;
          material?: string | null;
          dimensions?: string | null;
          unit?: string;
          price?: number;
          sf_per_sheet?: number | null;
          tax_rate?: number | null;
          base_price?: number | null;
          price_with_tax?: number | null;
          product_url?: string | null;
          image_url?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          price_last_updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          name: string;
          customer: string | null;
          address: string | null;
          quote_date: string;
          total_amount: number;
          status: string;
          project_type: string;
          other_expenses: number;
          other_expenses_label: string | null;
          tariff_multiplier: number;
          profit_multiplier: number;
          tax_percentage: number;
          install_delivery: number;
          install_delivery_usd: number;
          install_delivery_per_box_usd: number;
          referral_currency_rate: number;
          project_details: string | null;
          project_brief: string | null;
          disclaimer_tariff_info: string | null;
          disclaimer_price_validity: string | null;
          group_id: string | null;
          pdf_project_name: string | null;
          pdf_customer: string | null;
          pdf_address: string | null;
          pdf_project_brief: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          customer?: string | null;
          address?: string | null;
          quote_date?: string;
          total_amount?: number;
          status?: string;
          project_type?: string;
          other_expenses?: number;
          other_expenses_label?: string | null;
          tariff_multiplier?: number;
          profit_multiplier?: number;
          tax_percentage?: number;
          install_delivery?: number;
          install_delivery_usd?: number;
          install_delivery_per_box_usd?: number;
          referral_currency_rate?: number;
          project_details?: string | null;
          project_brief?: string | null;
          disclaimer_tariff_info?: string | null;
          disclaimer_price_validity?: string | null;
          group_id?: string | null;
          pdf_project_name?: string | null;
          pdf_customer?: string | null;
          pdf_address?: string | null;
          pdf_project_brief?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          customer?: string | null;
          address?: string | null;
          quote_date?: string;
          total_amount?: number;
          status?: string;
          project_type?: string;
          other_expenses?: number;
          other_expenses_label?: string | null;
          tariff_multiplier?: number;
          profit_multiplier?: number;
          tax_percentage?: number;
          install_delivery?: number;
          install_delivery_usd?: number;
          install_delivery_per_box_usd?: number;
          referral_currency_rate?: number;
          project_details?: string | null;
          project_brief?: string | null;
          disclaimer_tariff_info?: string | null;
          disclaimer_price_validity?: string | null;
          group_id?: string | null;
          pdf_project_name?: string | null;
          pdf_customer?: string | null;
          pdf_address?: string | null;
          pdf_project_brief?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      project_areas: {
        Row: {
          id: string;
          project_id: string;
          name: string;
          display_order: number;
          subtotal: number;
          applies_tariff: boolean;
          quantity: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          name: string;
          display_order?: number;
          subtotal?: number;
          applies_tariff?: boolean;
          quantity?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          name?: string;
          display_order?: number;
          subtotal?: number;
          applies_tariff?: boolean;
          quantity?: number;
          created_at?: string;
        };
      };
      settings: {
        Row: {
          id: string;
          key: string;
          value: string;
          category: string;
          description: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          value: string;
          category: string;
          description?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          value?: string;
          category?: string;
          description?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      team_members: {
        Row: {
          id: string;
          name: string;
          role: string | null;
          email: string | null;
          display_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          role?: string | null;
          email?: string | null;
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          role?: string | null;
          email?: string | null;
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
      };
      project_documents: {
        Row: {
          id: string;
          project_id: string;
          label: string;
          url: string;
          display_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          label: string;
          url?: string;
          display_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          label?: string;
          url?: string;
          display_order?: number;
          created_at?: string;
        };
      };
      project_tasks: {
        Row: {
          id: string;
          project_id: string;
          title: string;
          details: string | null;
          due_date: string | null;
          assignee_id: string | null;
          status: string;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          title: string;
          details?: string | null;
          due_date?: string | null;
          assignee_id?: string | null;
          status?: string;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          title?: string;
          details?: string | null;
          due_date?: string | null;
          assignee_id?: string | null;
          status?: string;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      project_activities: {
        Row: {
          id: string;
          project_id: string;
          name: string;
          start_date: string;
          end_date: string;
          display_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          name: string;
          start_date: string;
          end_date: string;
          display_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          name?: string;
          start_date?: string;
          end_date?: string;
          display_order?: number;
          created_at?: string;
        };
      };
      project_logs: {
        Row: {
          id: string;
          project_id: string;
          comment: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          comment: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          comment?: string;
          created_at?: string;
        };
      };
      closet_catalog: {
        Row: {
          id: string;
          cabinet_code: string;
          evita_line: string;
          description: string;
          height_in: number;
          width_in: number;
          depth_in: number;
          price_with_backs_usd: number | null;
          price_without_backs_usd: number | null;
          has_backs_option: boolean;
          boxes_count: number;
          dimensions_locked: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          cabinet_code: string;
          evita_line: string;
          description: string;
          height_in: number;
          width_in: number;
          depth_in: number;
          price_with_backs_usd?: number | null;
          price_without_backs_usd?: number | null;
          has_backs_option?: boolean;
          boxes_count?: number;
          dimensions_locked?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          cabinet_code?: string;
          evita_line?: string;
          description?: string;
          height_in?: number;
          width_in?: number;
          depth_in?: number;
          price_with_backs_usd?: number | null;
          price_without_backs_usd?: number | null;
          has_backs_option?: boolean;
          boxes_count?: number;
          dimensions_locked?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      area_closet_items: {
        Row: {
          id: string;
          area_id: string;
          closet_catalog_id: string;
          quantity: number;
          with_backs: boolean;
          unit_price_usd: number;
          unit_price_mxn: number;
          hardware: import('./database.types').Json;
          hardware_cost: number;
          subtotal_mxn: number;
          boxes_count: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          area_id: string;
          closet_catalog_id: string;
          quantity?: number;
          with_backs?: boolean;
          unit_price_usd?: number;
          unit_price_mxn?: number;
          hardware?: import('./database.types').Json;
          hardware_cost?: number;
          subtotal_mxn?: number;
          boxes_count?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          area_id?: string;
          closet_catalog_id?: string;
          quantity?: number;
          with_backs?: boolean;
          unit_price_usd?: number;
          unit_price_mxn?: number;
          hardware?: import('./database.types').Json;
          hardware_cost?: number;
          subtotal_mxn?: number;
          boxes_count?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      area_cabinets: {
        Row: {
          id: string;
          area_id: string;
          product_sku: string | null;
          quantity: number;
          box_material_id: string | null;
          box_edgeband_id: string | null;
          box_interior_finish_id: string | null;
          doors_material_id: string | null;
          doors_edgeband_id: string | null;
          doors_interior_finish_id: string | null;
          hardware: Json;
          accessories: Json;
          box_material_cost: number;
          box_edgeband_cost: number;
          box_interior_finish_cost: number;
          doors_material_cost: number;
          doors_edgeband_cost: number;
          doors_interior_finish_cost: number;
          hardware_cost: number;
          accessories_cost: number;
          labor_cost: number;
          subtotal: number;
          created_at: string;
          is_rta: boolean;
          use_back_panel_material: boolean;
          back_panel_material_id: string | null;
          back_panel_width_inches: number | null;
          back_panel_height_inches: number | null;
          back_panel_sf: number;
          back_panel_material_cost: number;
          original_back_panel_material_price: number | null;
          door_profile_id: string | null;
          door_profile_cost: number;
        };
        Insert: {
          id?: string;
          area_id: string;
          product_sku?: string | null;
          quantity?: number;
          box_material_id?: string | null;
          box_edgeband_id?: string | null;
          box_interior_finish_id?: string | null;
          doors_material_id?: string | null;
          doors_edgeband_id?: string | null;
          doors_interior_finish_id?: string | null;
          hardware?: Json;
          accessories?: Json;
          box_material_cost?: number;
          box_edgeband_cost?: number;
          box_interior_finish_cost?: number;
          doors_material_cost?: number;
          doors_edgeband_cost?: number;
          doors_interior_finish_cost?: number;
          hardware_cost?: number;
          accessories_cost?: number;
          labor_cost?: number;
          subtotal?: number;
          created_at?: string;
          is_rta?: boolean;
          use_back_panel_material?: boolean;
          back_panel_material_id?: string | null;
          back_panel_width_inches?: number | null;
          back_panel_height_inches?: number | null;
          back_panel_sf?: number;
          back_panel_material_cost?: number;
          original_back_panel_material_price?: number | null;
          door_profile_id?: string | null;
          door_profile_cost?: number;
        };
        Update: {
          id?: string;
          area_id?: string;
          product_sku?: string | null;
          quantity?: number;
          box_material_id?: string | null;
          box_edgeband_id?: string | null;
          box_interior_finish_id?: string | null;
          doors_material_id?: string | null;
          doors_edgeband_id?: string | null;
          doors_interior_finish_id?: string | null;
          hardware?: Json;
          accessories?: Json;
          box_material_cost?: number;
          box_edgeband_cost?: number;
          box_interior_finish_cost?: number;
          doors_material_cost?: number;
          doors_edgeband_cost?: number;
          doors_interior_finish_cost?: number;
          hardware_cost?: number;
          accessories_cost?: number;
          labor_cost?: number;
          subtotal?: number;
          created_at?: string;
          is_rta?: boolean;
          use_back_panel_material?: boolean;
          back_panel_material_id?: string | null;
          back_panel_width_inches?: number | null;
          back_panel_height_inches?: number | null;
          back_panel_sf?: number;
          back_panel_material_cost?: number;
          original_back_panel_material_price?: number | null;
          door_profile_id?: string | null;
          door_profile_cost?: number;
        };
      };
    };
  };
}
